### ISSUE TITLE
Generate Code for Solar Sensor

### ISSUE THREAD

**Issue by JonathanI19** [JonathanI19/EclipseBallooning#8]
We need to get basic code functionality with the solar sensor, as well as allow for switching between the two algorithms.

**Comment by JonathanI19** [comment]
@John0b1000 I have drafts of decode_brightness_into_action() and decode_darkness_into_action() complete. Additionally, I should have everything handled in main.py as well.

There are a couple points of note though:
- Can you look at the conditions marked with `########################## IMPORTANT ##########################` in solar_sensor_decoder.py? These are there to prevent the edge case where we have two equivalent adc values, but I'm not sure if this is the best way to handle it. Let me know what you think.
- We still need to read the adc values into the script. I believe you said you already wrote that? Do you want to implement that or point me to where I can find that code?

**Comment by John0b1000** [comment]
Everything looks good. I will take another look tomorrow, but that seems like a valid way to handle the Q1/Q3 case.

For the Pi serial stuff, here is what I found: https://raspberrypi.stackexchange.com/questions/99138/how-to-send-and-read-a-string-from-raspberry-pi-to-arduino-via-serial-interface. Currently, the Arduino writes the four values individually, but we should agree on a common string format for the Arduino to output so that the Pi can easily parse it.

**Comment by JonathanI19** [comment]
Arduino string needs to end with '/n'. See readline()

**Comment by John0b1000** [comment]
Awesome. I will prepare the **ArduinoADC** branch for merge and update the format there.
